Sudoku Solver/Models/SudokuModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Web;

namespace Sudoku_Solver.Models
{
    public class SudokuModel
    {
        [Range(0, 9, ErrorMessage = "Error")]
        public List<int> board { get; set; } = new List<int>();

        public SudokuModel()
        {
            for(int i = 0; i < 81; i++)
            {
                board.Add(0);
            }
        }
    }
}

Sudoku Solver/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sudoku_Solver.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Sudoku Solver/Controllers/SudokuController.cs
using Sudoku_Solver.Classes;
using Sudoku_Solver.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sudoku_Solver.Controllers
{
    public class SudokuController : Controller
    {
        private SudokuSolver solver = new SudokuSolver();

        public ActionResult Index()
        {
            var sudoku = new SudokuModel();
            return View(sudoku);
        }

        [HttpPost]
        public ActionResult Index(SudokuModel model)
        {
            TempData["sudoku"] = model;
            return RedirectToAction("Solve");
        }

        public ActionResult Solve()
        {
            if (TempData["sudoku"] != null)
            {
                SudokuModel sudoku = (SudokuModel)TempData["sudoku"];
                TempData.Remove("sudoku");

                if (solver.AttemptSolve(sudoku.board))
                {
                    return View(sudoku);
                }
                {
                    return RedirectToAction("Unsolvable");
                }
            }

            return View();
        }

        public ActionResult Generate()
        {
            var sudoku = new SudokuModel();
            var generator = new SudokuGenerator();

            sudoku.board = generator.board;

            return View(sudoku);
        }

        [HttpPost]
        public ActionResult Generate(SudokuModel model)
        {
            TempData["sudoku"] = model;
            return RedirectToAction("Solve");
        }

        public ActionResult Unsolvable()
        {
            return View();
        }
    }
}

Sudoku Solver/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Sudoku Solver/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Sudoku Solver/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome</h1>
    <p class="lead">This is Sudoku Solver.</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

@*<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

Sudoku Solver/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sudoku Solver</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sudoku Solver", "Index", "Sudoku")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sudoku Solver Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Sudoku Solver/Views/Sudoku/Generate.cshtml
@model Sudoku_Solver.Models.SudokuModel

@{
    ViewBag.Title = "Generate";
}

@using (Html.BeginForm())
{
    <center>
        <h2>Generated Sudoku</h2>

        @for (int i = 0; i < 9; i++)
        {
            <div class="row">
                @{int row = i * 9;}
                @for (int j = row; j < row + 9; j++)
                {
                    @Html.EditorFor(Model => Model.board[j], new { htmlAttributes = new { @class = "form-controll", style = "width: 40px" } })
                    @Html.ValidationMessageFor(Model => Model.board[j], "", new { @class = "text-danger" })
                }
            </div>
        }

        <div class="row">
            <input type="submit" value="Solve" class="btn btn-default">
        </div>
    </center>
}

Sudoku Solver/Views/Sudoku/Index.cshtml
@model Sudoku_Solver.Models.SudokuModel

@{
    ViewBag.Title = "Sudoku";
}

@using (Html.BeginForm())
{
    <center>
        <h2>Sudoku Solver</h2>

        @for (int i = 0; i < 9; i++)
        {
            <div class="row">
                @{int row = i * 9;}
                @for (int j = row; j < row + 9; j++)
                {
                    @Html.EditorFor(Model => Model.board[j], new { htmlAttributes = new { @class = "form-controll", style = "width: 40px" } })
                    @Html.ValidationMessageFor(Model => Model.board[j], "", new { @class = "text-danger" })
                }
            </div>
        }

        <div class="row">
            <input type="button" value="Generate" class="btn btn-default" onclick="location.href='@Url.Action("Generate", "Sudoku")'" />
            <input type="submit" value="Solve" class="btn btn-default">
        </div>
    </center>
}

Sudoku Solver/Views/Sudoku/Solve.cshtml
@model Sudoku_Solver.Models.SudokuModel
@{
    ViewBag.Title = "Solve";
}

@using (Html.BeginForm())
{
    <center>
        <h2>The Solved Solution</h2>

        @for (int i = 0; i < 9; i++)
        {
            <div class="row">
                @{int row = i * 9;}
                @for (int j = row; j < row + 9; j++)
                {
                    @Html.EditorFor(Model => Model.board[j], new { htmlAttributes = new { @class = "form-controll", style = "width: 40px" } })
                }
            </div>
        }
    </center>
}

Sudoku Solver/Views/Sudoku/Unsolvable.cshtml
@{
    ViewBag.Title = "Unsolvable";
}

<h2>Unsolvable</h2>

<p>The Sudoku was unsolvable</p>